# Generated by Django 4.1.4 on 2023-01-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="stud_Reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.IntegerField()),
                ("place", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=20)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app35.login"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=20)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app35.login"
                    ),
                ),
            ],
        ),
    ]
